
version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    working_dir: /var/www
    env_file: .env
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=27017"
      - "DB_HOST=mongo"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    working_dir: /var/www/public
    volumes_from:
      - app
    ports:
      - 80:80

  # The Database
  mongo:
     image: mongo:latest
     container_name: "mongodb"
     environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
     volumes:
       - ./data/db:/data/db
     ports:
         - 27017:27017
     command: mongod --smallfiles --logpath=/dev/null # --quiet
