branch-defaults:
  dev:
    environment: ADW-Laravel-A2-dev
    group_suffix: null
global:
  application_name: ADW_Laravel_A2
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Multi-container Docker 17.12.0-ce (Generic)
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
