branch-defaults:
  Deployment:
    environment: webassignment-dev
    group_suffix: null
  master:
    environment: webassignment-dev
global:
  application_name: webassignment
  branch: null
  default_ec2_keyname: null
  default_platform: Multi-container Docker 17.09.1-ce (Generic)
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
